  kafka1:
    image: index.alauda.cn/knarfeh/catalog-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka1
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 172.31.6.103
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  123.56.235.98:2181

  kafka2:
    image: index.alauda.cn/knarfeh/catalog-kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka2
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 172.31.6.103
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  123.56.235.98:2181
